language: smalltalk
sudo: false
addons:
    apt:
    packages:
        - libssl1.0.2
smalltalk:
    - Pharo-5.0
env:
    global:
        - BASELINE="BormModel"
        - TESTS="Borm.*"
        - PACKAGES="/repository"
        - BASELINE_GROUP="default"
