language: smalltalk
sudo: false
smalltalk:
    - Pharo-5.0
env:
    global:
        - BASELINE="BormModel"
        - TESTS="Borm.*"
        - PACKAGES="/repository"
        - BASELINE_GROUP="default"
